version: '3.9'
name: library
services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_USER: alien
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: library_data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    name: library-db-data
